### ISSUE TITLE
Listens on all interfaces

### ISSUE THREAD

**Issue by enocom** [cloudfoundry/statsd-injector#2]
The code doesn't limit the interfaces it listens on which is potentially a security issue.

**Comment by jasonkeene** [comment]
Here is the line in question:

https://github.com/cloudfoundry/statsd-injector/blob/0ae51cfc2f0d87969723930ad11b0482861fb5cd/statsdlistener/statsd_listener.go#L26

We should certainly not listen on all ports. This should default to localhost and possibly be configurable;.
